version: '3.8'

services:
  app:
    build: ./mini-ticketing-system-laravel
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./mini-ticketing-system-laravel:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:056psArsIIWKuJMxaMeDeEHboqZKunqBK/iQbQX/1uI=
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo_db
      - DB_PORT=27017
      - DB_DATABASE=ticket_system
      - DB_USERNAME=
      - DB_PASSWORD=
      # - MONGODB_URI=mongodb://mongo_db:27017

  frontend:
    build: ./ticketing-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./ticketing-frontend:/app
    command: npm run dev
    depends_on:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - ./data/db:/data/db
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=adminpassword
  #   networks:
  #     - mongodb_network

# volumes:
#   mongodb_data:

networks:
  mongodb_network:
    driver: bridge